name: seller_management
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.1+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  extended_image: ^9.0.7
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flex_color_scheme: ^8.0.0
  gap: ^3.0.1
  material_design_icons_flutter: ^7.0.7296
  badges: ^3.1.2
  grouped_list: ^6.0.0
  flutter_form_builder: ^9.3.0
  flutter_svg: ^2.0.10
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.1.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  buttons_tabbar: ^1.3.12
  shimmer_animation: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter_html: ^3.0.0-beta.2
  html_editor_enhanced_plus: ^2.6.0
  toastification: ^2.0.0
  pull_to_refresh: ^2.0.0
  animated_segmented_tab_control: ^2.0.0
  flutter_inappwebview: ^6.0.0
  syncfusion_flutter_charts:
    git:
      url: https://github.com/Luvti/flutter-widgets
      path: packages/syncfusion_flutter_charts
      ref: 15e3c4a95e3cf2e2393755bf5aa11c0206ed6dea
  flutter_parsed_text: ^2.2.1
  intl_utils: ^2.8.7

  # State and Management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.1
  shared_preferences: ^2.2.3
  get_it: ^8.0.2

  # Util
  intl: ^0.19.0
  dio: ^5.5.0
  pretty_dio_logger: ^1.3.1
  fpdart: ^1.1.0
  path_provider: ^2.1.3
  file_picker: ^8.0.5
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  image_picker: ^1.1.2
  open_filex: ^4.4.0
  collection: ^1.18.0
  # easy_localization: ^3.0.7
  form_builder_validators: ^11.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  permission_handler: ^11.3.1
  timeago: ^3.6.1
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  flutter_local_notifications: ^18.0.1
  background_downloader: ^9.1.1
  device_info_plus: ^11.1.1

  #payment
  payment_module:
    path: package/payment_module
  esewa_flutter_sdk:
    path: package/esewa_flutter_sdk
  # razorpay_flutter: ^1.3.5
  pointycastle: ^3.9.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  webview_flutter_android: 3.16.1

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/svg/
    - assets/svg/nav/
    - assets/svg/dash/
    - assets/lottie/
    - assets/icon/
    - assets/png/
    - assets/illustration/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"

flutter_intl:
  enabled: true
  class_name: TR
  main_locale: en
  arb_dir: lib/_core/l10n/lang
  output_dir: lib/_core/l10n/gen
