name: payment_module
description: A package to manage app payment methods for igen solution
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.4
  flutter: ^3.19.6

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  intl: ^0.19.0
  fpdart: ^1.1.0
  dio: ^5.5.0
  pretty_dio_logger: ^1.3.1
  aamarpay: ^1.0.10
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
